import { Recipe } from './recipe.model';

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 1,
    nombre: 'Vori-Vori',
    descripcion: 'El Vori Vori es una sopa tradicional paraguaya hecha con bolitas de queso y harina de maíz, cocinadas en un caldo de pollo rico y sabroso.',
    categorias: ['Almuerzo', 'Salados'],
    ingredientes: [
      { nombre: 'Pollo', cantidad: '500', unidad: 'g' },
      { nombre: 'Harina de maíz', cantidad: '200', unidad: 'g' },
      { nombre: 'Queso paraguayo rallado', cantidad: '150', unidad: 'g' },
      { nombre: 'Cebolla', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Ajo', cantidad: '3', unidad: 'dientes' },
      { nombre: 'Caldo de pollo', cantidad: '2', unidad: 'litros' },
    ],
    infoNutricional: {
      calorias: 380,
      proteinas: 28,
      carbohidratos: 35,
      grasas: 12,
    },
    isFavorite: false,
    isPopular: true,
  },
  {
    id: 2,
    nombre: 'Tortas de Avena con Proteina',
    descripcion: 'Las tortitas de avena con proteína son rápidas, fáciles de hacer y llenas de fibra y potentes vitaminas, que ayudan a promover el crecimiento muscular.',
    categorias: ['Desayuno', 'Saludables', 'Masa Muscular'],
    ingredientes: [
      { nombre: 'Avena en hojuelas', cantidad: '100', unidad: 'g' },
      { nombre: 'Huevos', cantidad: '3', unidad: 'unidades' },
      { nombre: 'Proteína en polvo', cantidad: '30', unidad: 'g' },
      { nombre: 'Leche', cantidad: '100', unidad: 'ml' },
      { nombre: 'Canela', cantidad: '1', unidad: 'cucharadita' },
    ],
    infoNutricional: {
      calorias: 320,
      proteinas: 32,
      carbohidratos: 30,
      grasas: 8,
    },
    isFavorite: false,
    isPopular: true,
  },
  {
    id: 3,
    nombre: 'Licuado Verde',
    descripcion: 'Batido verde refrescante lleno de nutrientes esenciales, perfecto para comenzar el día con energía.',
    categorias: ['Desayuno', 'Saludables', 'Bajar de Peso'],
    ingredientes: [
      { nombre: 'Espinaca', cantidad: '2', unidad: 'tazas' },
      { nombre: 'Plátano', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Manzana verde', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Agua o leche de almendras', cantidad: '250', unidad: 'ml' },
      { nombre: 'Jengibre', cantidad: '1', unidad: 'cm' },
    ],
    infoNutricional: {
      calorias: 150,
      proteinas: 3,
      carbohidratos: 35,
      grasas: 1,
    },
    isFavorite: false,
    isPopular: true,
  },
  {
    id: 4,
    nombre: 'Pie de Limón',
    descripcion: 'Un delicioso pie con base de galleta, relleno cremoso de limón y merengue suave por encima.',
    categorias: ['Merienda', 'Dulces'],
    ingredientes: [
      { nombre: 'Galletas María', cantidad: '300', unidad: 'g' },
      { nombre: 'Mantequilla', cantidad: '100', unidad: 'g' },
      { nombre: 'Leche condensada', cantidad: '400', unidad: 'g' },
      { nombre: 'Jugo de limón', cantidad: '150', unidad: 'ml' },
      { nombre: 'Huevos', cantidad: '4', unidad: 'unidades' },
      { nombre: 'Azúcar', cantidad: '100', unidad: 'g' },
    ],
    infoNutricional: {
      calorias: 420,
      proteinas: 8,
      carbohidratos: 58,
      grasas: 18,
    },
    isFavorite: false,
    isPopular: true,
  },
  {
    id: 5,
    nombre: 'Tallarín con Salsa Alfredo',
    descripcion: 'Pasta cremosa con una deliciosa salsa Alfredo casera, rica en sabor y textura.',
    categorias: ['Almuerzo', 'Cena', 'Salados'],
    ingredientes: [
      { nombre: 'Tallarines', cantidad: '400', unidad: 'g' },
      { nombre: 'Crema de leche', cantidad: '300', unidad: 'ml' },
      { nombre: 'Queso parmesano', cantidad: '100', unidad: 'g' },
      { nombre: 'Ajo', cantidad: '3', unidad: 'dientes' },
      { nombre: 'Mantequilla', cantidad: '50', unidad: 'g' },
      { nombre: 'Sal y pimienta', cantidad: 'al gusto', unidad: '' },
    ],
    infoNutricional: {
      calorias: 520,
      proteinas: 18,
      carbohidratos: 52,
      grasas: 28,
    },
    isFavorite: false,
    isPopular: true,
  },
  {
    id: 6,
    nombre: 'Chipá Só\'o',
    descripcion: 'Pan de queso paraguayo relleno de carne molida, perfecto para el desayuno o merienda.',
    categorias: ['Desayuno', 'Merienda', 'Salados'],
    ingredientes: [
      { nombre: 'Almidón de mandioca', cantidad: '500', unidad: 'g' },
      { nombre: 'Queso paraguayo', cantidad: '300', unidad: 'g' },
      { nombre: 'Carne molida', cantidad: '250', unidad: 'g' },
      { nombre: 'Huevos', cantidad: '3', unidad: 'unidades' },
      { nombre: 'Cebolla', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Leche', cantidad: '100', unidad: 'ml' },
    ],
    infoNutricional: {
      calorias: 380,
      proteinas: 22,
      carbohidratos: 42,
      grasas: 14,
    },
    isFavorite: false,
    isPopular: true,
  },
  {
    id: 7,
    nombre: 'Ensalada César con Pollo',
    descripcion: 'Ensalada clásica con pollo a la parrilla, lechuga romana, crutones y aderezo César.',
    categorias: ['Almuerzo', 'Cena', 'Saludables', 'Bajar de Peso'],
    ingredientes: [
      { nombre: 'Pechuga de pollo', cantidad: '300', unidad: 'g' },
      { nombre: 'Lechuga romana', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Pan para crutones', cantidad: '100', unidad: 'g' },
      { nombre: 'Queso parmesano', cantidad: '50', unidad: 'g' },
      { nombre: 'Aderezo César', cantidad: '100', unidad: 'ml' },
    ],
    infoNutricional: {
      calorias: 380,
      proteinas: 35,
      carbohidratos: 18,
      grasas: 18,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 8,
    nombre: 'Omelette de Vegetales',
    descripcion: 'Omelette esponjoso cargado de vegetales frescos, ideal para un desayuno nutritivo.',
    categorias: ['Desayuno', 'Saludables', 'Bajar de Peso'],
    ingredientes: [
      { nombre: 'Huevos', cantidad: '3', unidad: 'unidades' },
      { nombre: 'Pimiento rojo', cantidad: '1/2', unidad: 'unidad' },
      { nombre: 'Cebolla', cantidad: '1/4', unidad: 'unidad' },
      { nombre: 'Tomate', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Espinaca', cantidad: '1', unidad: 'taza' },
      { nombre: 'Queso bajo en grasa', cantidad: '30', unidad: 'g' },
    ],
    infoNutricional: {
      calorias: 220,
      proteinas: 18,
      carbohidratos: 8,
      grasas: 14,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 9,
    nombre: 'Sopa de Pollo y Quinoa',
    descripcion: 'Sopa reconfortante con pollo, quinoa y vegetales, perfecta para una comida ligera.',
    categorias: ['Almuerzo', 'Cena', 'Saludables'],
    ingredientes: [
      { nombre: 'Pechuga de pollo', cantidad: '300', unidad: 'g' },
      { nombre: 'Quinoa', cantidad: '100', unidad: 'g' },
      { nombre: 'Zanahoria', cantidad: '2', unidad: 'unidades' },
      { nombre: 'Apio', cantidad: '2', unidad: 'tallos' },
      { nombre: 'Caldo de pollo', cantidad: '1.5', unidad: 'litros' },
      { nombre: 'Ajo y cebolla', cantidad: 'al gusto', unidad: '' },
    ],
    infoNutricional: {
      calorias: 280,
      proteinas: 28,
      carbohidratos: 32,
      grasas: 5,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 10,
    nombre: 'Brownies de Chocolate',
    descripcion: 'Brownies densos y chocolatosos, perfectos para satisfacer el antojo de dulce.',
    categorias: ['Merienda', 'Dulces'],
    ingredientes: [
      { nombre: 'Chocolate oscuro', cantidad: '200', unidad: 'g' },
      { nombre: 'Mantequilla', cantidad: '150', unidad: 'g' },
      { nombre: 'Azúcar', cantidad: '200', unidad: 'g' },
      { nombre: 'Huevos', cantidad: '3', unidad: 'unidades' },
      { nombre: 'Harina', cantidad: '120', unidad: 'g' },
      { nombre: 'Cacao en polvo', cantidad: '30', unidad: 'g' },
    ],
    infoNutricional: {
      calorias: 450,
      proteinas: 6,
      carbohidratos: 55,
      grasas: 24,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 11,
    nombre: 'Batido Proteico de Banana',
    descripcion: 'Batido post-entreno con proteína, banana y mantequilla de maní para recuperación muscular.',
    categorias: ['Merienda', 'Saludables', 'Masa Muscular'],
    ingredientes: [
      { nombre: 'Plátano', cantidad: '2', unidad: 'unidades' },
      { nombre: 'Proteína en polvo', cantidad: '40', unidad: 'g' },
      { nombre: 'Leche', cantidad: '300', unidad: 'ml' },
      { nombre: 'Mantequilla de maní', cantidad: '2', unidad: 'cucharadas' },
      { nombre: 'Avena', cantidad: '30', unidad: 'g' },
    ],
    infoNutricional: {
      calorias: 420,
      proteinas: 38,
      carbohidratos: 48,
      grasas: 12,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 12,
    nombre: 'Arroz Integral con Vegetales',
    descripcion: 'Arroz integral salteado con vegetales coloridos, bajo en calorías y alto en fibra.',
    categorias: ['Almuerzo', 'Cena', 'Saludables', 'Bajar de Peso'],
    ingredientes: [
      { nombre: 'Arroz integral', cantidad: '200', unidad: 'g' },
      { nombre: 'Brócoli', cantidad: '1', unidad: 'taza' },
      { nombre: 'Zanahoria', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Pimiento', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Salsa de soja baja en sodio', cantidad: '2', unidad: 'cucharadas' },
      { nombre: 'Ajo y jengibre', cantidad: 'al gusto', unidad: '' },
    ],
    infoNutricional: {
      calorias: 280,
      proteinas: 8,
      carbohidratos: 52,
      grasas: 4,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 13,
    nombre: 'Panqueques de Plátano',
    descripcion: 'Panqueques naturalmente dulces hechos solo con plátano y huevos, sin azúcar añadida.',
    categorias: ['Desayuno', 'Saludables', 'Dulces'],
    ingredientes: [
      { nombre: 'Plátanos maduros', cantidad: '2', unidad: 'unidades' },
      { nombre: 'Huevos', cantidad: '2', unidad: 'unidades' },
      { nombre: 'Canela', cantidad: '1', unidad: 'cucharadita' },
      { nombre: 'Aceite de coco', cantidad: '1', unidad: 'cucharada' },
    ],
    infoNutricional: {
      calorias: 220,
      proteinas: 12,
      carbohidratos: 32,
      grasas: 6,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 14,
    nombre: 'Empanadas de Carne',
    descripcion: 'Empanadas crujientes rellenas de carne molida sazonada con especias.',
    categorias: ['Almuerzo', 'Merienda', 'Cena', 'Salados'],
    ingredientes: [
      { nombre: 'Masa para empanadas', cantidad: '12', unidad: 'unidades' },
      { nombre: 'Carne molida', cantidad: '500', unidad: 'g' },
      { nombre: 'Cebolla', cantidad: '2', unidad: 'unidades' },
      { nombre: 'Huevos duros', cantidad: '2', unidad: 'unidades' },
      { nombre: 'Aceitunas', cantidad: '12', unidad: 'unidades' },
      { nombre: 'Comino y pimentón', cantidad: 'al gusto', unidad: '' },
    ],
    infoNutricional: {
      calorias: 320,
      proteinas: 18,
      carbohidratos: 28,
      grasas: 16,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 15,
    nombre: 'Yogur Griego con Frutas',
    descripcion: 'Yogur griego natural con frutas frescas y granola, perfecto para el desayuno.',
    categorias: ['Desayuno', 'Merienda', 'Saludables', 'Bajar de Peso'],
    ingredientes: [
      { nombre: 'Yogur griego natural', cantidad: '200', unidad: 'g' },
      { nombre: 'Fresas', cantidad: '5', unidad: 'unidades' },
      { nombre: 'Arándanos', cantidad: '50', unidad: 'g' },
      { nombre: 'Granola', cantidad: '30', unidad: 'g' },
      { nombre: 'Miel', cantidad: '1', unidad: 'cucharada' },
    ],
    infoNutricional: {
      calorias: 280,
      proteinas: 18,
      carbohidratos: 38,
      grasas: 6,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 16,
    nombre: 'Pollo a la Parrilla con Especias',
    descripcion: 'Pechuga de pollo marinada con especias y cocida a la parrilla, jugosa y sabrosa.',
    categorias: ['Almuerzo', 'Cena', 'Saludables', 'Masa Muscular'],
    ingredientes: [
      { nombre: 'Pechuga de pollo', cantidad: '400', unidad: 'g' },
      { nombre: 'Limón', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Ajo en polvo', cantidad: '1', unidad: 'cucharadita' },
      { nombre: 'Paprika', cantidad: '1', unidad: 'cucharadita' },
      { nombre: 'Orégano', cantidad: '1', unidad: 'cucharadita' },
      { nombre: 'Aceite de oliva', cantidad: '2', unidad: 'cucharadas' },
    ],
    infoNutricional: {
      calorias: 240,
      proteinas: 42,
      carbohidratos: 2,
      grasas: 8,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 17,
    nombre: 'Tarta de Manzana',
    descripcion: 'Tarta casera con manzanas caramelizadas y masa crujiente.',
    categorias: ['Merienda', 'Dulces'],
    ingredientes: [
      { nombre: 'Manzanas verdes', cantidad: '5', unidad: 'unidades' },
      { nombre: 'Masa para tarta', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Azúcar morena', cantidad: '100', unidad: 'g' },
      { nombre: 'Mantequilla', cantidad: '50', unidad: 'g' },
      { nombre: 'Canela', cantidad: '2', unidad: 'cucharaditas' },
      { nombre: 'Huevo (para pintar)', cantidad: '1', unidad: 'unidad' },
    ],
    infoNutricional: {
      calorias: 340,
      proteinas: 4,
      carbohidratos: 52,
      grasas: 14,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 18,
    nombre: 'Wrap de Pollo y Aguacate',
    descripcion: 'Wrap saludable con pollo, aguacate, lechuga y aderezo ligero.',
    categorias: ['Almuerzo', 'Merienda', 'Saludables', 'Bajar de Peso'],
    ingredientes: [
      { nombre: 'Tortilla integral', cantidad: '2', unidad: 'unidades' },
      { nombre: 'Pechuga de pollo', cantidad: '200', unidad: 'g' },
      { nombre: 'Aguacate', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Lechuga', cantidad: '2', unidad: 'hojas' },
      { nombre: 'Tomate', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Yogur griego (aderezo)', cantidad: '3', unidad: 'cucharadas' },
    ],
    infoNutricional: {
      calorias: 380,
      proteinas: 32,
      carbohidratos: 35,
      grasas: 14,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 19,
    nombre: 'Salmón al Horno con Limón',
    descripcion: 'Filete de salmón horneado con limón y hierbas, rico en omega-3.',
    categorias: ['Almuerzo', 'Cena', 'Saludables', 'Masa Muscular'],
    ingredientes: [
      { nombre: 'Filete de salmón', cantidad: '300', unidad: 'g' },
      { nombre: 'Limón', cantidad: '1', unidad: 'unidad' },
      { nombre: 'Aceite de oliva', cantidad: '2', unidad: 'cucharadas' },
      { nombre: 'Eneldo fresco', cantidad: '2', unidad: 'cucharadas' },
      { nombre: 'Ajo', cantidad: '2', unidad: 'dientes' },
    ],
    infoNutricional: {
      calorias: 320,
      proteinas: 38,
      carbohidratos: 2,
      grasas: 18,
    },
    isFavorite: false,
    isPopular: false,
  },
  {
    id: 20,
    nombre: 'Galletas de Avena y Pasas',
    descripcion: 'Galletas caseras crujientes con avena y pasas, perfectas para la merienda.',
    categorias: ['Merienda', 'Dulces', 'Saludables'],
    ingredientes: [
      { nombre: 'Avena en hojuelas', cantidad: '200', unidad: 'g' },
      { nombre: 'Harina integral', cantidad: '100', unidad: 'g' },
      { nombre: 'Pasas', cantidad: '80', unidad: 'g' },
      { nombre: 'Miel', cantidad: '80', unidad: 'g' },
      { nombre: 'Aceite de coco', cantidad: '60', unidad: 'g' },
      { nombre: 'Huevo', cantidad: '1', unidad: 'unidad' },
    ],
    infoNutricional: {
      calorias: 180,
      proteinas: 4,
      carbohidratos: 28,
      grasas: 6,
    },
    isFavorite: false,
    isPopular: false,
  },
];
